# Generated by Django 4.0.4 on 2022-05-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_taguserchoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagUserChoice',
        ),
    ]
