# Generated by Django 4.0.4 on 2022-05-19 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0005_delete_taguserchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagUserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ManyToManyField(through='news.TagUserChoice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taguserchoice',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.tag'),
        ),
        migrations.AddField(
            model_name='taguserchoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
