# Generated by Django 4.0.4 on 2022-05-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
